behaviors:
  JumpAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 1.0e-4
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 3
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
      curiosity:
        strength: 0.01    # How strong the curiosity reward is
        gamma: 0.99
      gail:
        strength: 0.2
        demo_path: Assets/Demonstrations
    behavioral_cloning:
      demo_path: Assets/Demonstrations
      strength: 0.9
      steps: 100000
      samples_per_update: 100
    max_steps: 5e6
    time_horizon: 64
    summary_freq: 5000
    checkpoint_interval: 50000
    keep_checkpoints: 5
    threaded: true
